name: speech_recorder_example
description: "A new Flutter project."
resolution: workspace
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  speech_recorder:
    path: ../
  speech_utils:
    path: ../../speech_utils
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.0
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  record_windows:
    git:
      url: https://github.com/hipposphere/record_fork.git
      ref: advanced-recorder
      path: record_windows

flutter:
  uses-material-design: true
