name: speech_recorder_example
description: "A new Flutter project."
resolution: workspace
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  speech_recorder:
    path: ../
  speech_utils:
    path: ../../speech_utils
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.54
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.3
  hippo_core:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.4
  hippo_core_flutter:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.4
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
