name: hippo_utils
description: A new Flutter package project.
version: 0.1.6
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  rxdart: any
  url_launcher: 6.3.2
  uuid: 4.5.1
  web: 1.1.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0-beta.4
  cross_file: ^0.3.5
  archive: ^4.0.7
  file_picker: ^10.3.3
  filesize: ^2.0.1
  mime: ^2.0.0
  intl: any
  isoweek: ^1.1.4
  file_saver: ^0.3.1
  audioplayers: ^6.5.1
  audioplayers_web: ^5.1.1
  file_selector: ^1.0.4
  share_plus: ^12.0.1
  posthog_flutter: ^5.6.0
  content_resolver: ^0.3.6
  package_info_plus: ^9.0.0
  app_links: 6.4.1
  path: ^1.9.1
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
