name: dictation_support_example
description: "A new Flutter project."
resolution: workspace
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dictation_support:
    path: ../
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.43
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
