name: hippo_auth_example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  hippo_auth:
    path: ../
  hippo_auth_ui:
    path: ../../hippo_auth_ui
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.53
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.2
  hippo_core:
    hosted: https://pub.hippolabs.org
    version: ^0.1.10
  hippo_core_flutter:
    hosted: https://pub.hippolabs.org
    version: ^0.1.13
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
