name: postgres_base_models
description: Provider-Like State-Management-System and more useful tools
version: 0.1.0
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.11.0 < 4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.1.0
  test: any
