name: hippo_auth_backend
description: A backend for the Hippo authentication system.
version: 0.1.10
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.12.0 < 4.0.0"

dependencies:
  dart_edge_core:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.17
  dart_edge_sql:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.21
  dart_edge_http_server_runtime:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.19
  dart_edge_jaspr:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.6
  dart_edge_auth:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.18
  jaspr: ^0.23.1


dev_dependencies:
  build_runner: ^2.15.0
  dart_edge_http_server:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.14
  test: ^1.30.0
