name: speech_utils
description: Utilities for PCM16 speech segmentation, segmented capture, and AAC compression.
version: 0.3.1
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.12.0 < 4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  speech_utils_android:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.1
  speech_utils_core:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.0
  speech_utils_ios:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.1
  speech_utils_linux:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.1
  speech_utils_macos:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.1
  speech_utils_platform_interface:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.1
  speech_utils_vad_ten:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.1
  speech_utils_windows:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.1
  cross_file: ^0.3.5+4
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
  test: ^1.31.1

flutter:
  plugin:
    platforms:
      android:
        default_package: speech_utils_android
      ios:
        default_package: speech_utils_ios
      linux:
        default_package: speech_utils_linux
      macos:
        default_package: speech_utils_macos
      windows:
        default_package: speech_utils_windows
