export 'package:cross_file/cross_file.dart' show XFile;
export 'package:speech_utils_core/speech_utils_core.dart';
export 'package:speech_utils_platform_interface/speech_utils_platform_interface.dart'
    show NativeAudioRecorderCapabilities, NativeAudioRecorderPlatform, SpeechUtilsPlatform;
export 'src/encoding/aac_encoder.dart';
export 'src/encoding/ffmpeg_aac_encoder.dart';
export 'src/encoding/native_audio_encoder.dart';
export 'src/metadata/native_audio_metadata_reader.dart';
export 'src/models/audio_metadata.dart';
export 'src/models/audio_segment_metrics.dart';
export 'src/models/pause_split_options.dart';
export 'src/models/input_device.dart';
export 'src/models/pcm16_snippet.dart';
export 'src/models/segmented_audio_capture.dart';
export 'src/models/voice_activity_metadata.dart';
export 'src/recording/audio_recorder_config.dart';
export 'src/recording/native_audio_recorder.dart';
export 'src/recording/voice_segment.dart';
export 'src/utils/amplitude_waveform_utils.dart';
export 'src/splitting/pcm16_stream_pause_splitter.dart';
export 'src/speech_utils.dart';
export 'src/vad/energy_vad_backend.dart';
export 'src/vad/speech_vad_config.dart';
export 'src/vad/ten_vad_ffi_backend.dart';
export 'src/vad/vad_backend.dart';
