name: speech_recorder
description: "A useful speech recorder abstraction"
version: 0.1.0
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  record: "6.2.0"
  cross_file: "^0.3.5+2"
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.18
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.24
  speech_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
