name: speech_utils_android
description: Android AudioRecord, MediaRecorder, and MediaCodec AAC implementation for speech_utils.
version: 0.3.1
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  code_assets: ^1.2.1
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  hooks: ^2.0.2
  jni: ^1.0.0
  jni_flutter: ^1.0.1
  native_toolchain_c: ^0.19.2
  path: ^1.9.1
  speech_utils_core:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.0
  speech_utils_platform_interface:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  jnigen: ^0.16.0
  lints: ^6.1.0

flutter:
  plugin:
    implements: speech_utils
    platforms:
      android:
        package: org.hippolabs.speech_utils
        pluginClass: SpeechUtilsPlugin
        dartPluginClass: SpeechUtilsAndroid
