name: hippo_auth_ui
description: Flutter UI components and login flows for hippo_auth
version: 0.1.0
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.12.0 < 4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  hippo_auth:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.2.0
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.53
  hippo_core:
    hosted: https://pub.hippolabs.org
    version: ^0.1.5
  hippo_core_flutter:
    hosted: https://pub.hippolabs.org
    version: ^0.1.6
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
