name: hippo_components
description: Comprehensive Flutter UI component library featuring modals, charts, themes, sliver utilities, and cross-platform adaptive widgets for Hipposphere applications.
version: 0.1.32
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  forui: 0.19.0
  super_context_menu: ^0.9.1
  wolt_modal_sheet: 0.11.0
  soft_edge_blur: 0.1.3
  super_sliver_list: 0.4.1
  auto_size_text: ^3.0.0
  flutter_svg: ^2.2.4
  url_launcher: ^6.3.2
  skeletonizer: ^2.1.3
  pencil_kit: ^2.1.1
  lottie: ^3.3.2
  gpt_markdown: ^1.1.5
  flutter_markdown: ^0.7.7
  webview_flutter_web: ^0.2.3+4
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.4.0+2
  sliver_tools: ^0.2.12
  html2md: ^1.3.2
  community_charts_flutter: 1.0.4
  pull_down_button: ^0.10.2
  glow_container: ^1.0.1
  flutter_resizable_container: ^4.2.0
  cupertino_calendar_picker: ^2.2.6
  toastification: ^3.0.3
  webview_flutter: ^4.13.1
  decimal: ^3.2.4
  pinput: ^6.0.2
  percent_indicator: 4.2.5
  html: ^0.15.6
  qr_flutter: ^4.1.0
  timeago: 3.7.1
  shimmer: 3.0.0
  # Local Packages
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  assets:
    - assets/
    - assets/other/
