name: speech_utils_example
description: "Flutter example for speech_utils."
resolution: workspace
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  speech_utils:
    path: ../
  hippo_components:
    path: ../../hippo_components
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
