name: desktop_autopaste
description: Desktop auto-paste utilities implemented via native FFI code assets.
version: 0.2.17
resolution: workspace
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"

environment:
  sdk: ">=3.12.0 < 4.0.0"
  flutter: ">=3.44.0"

dependencies:
  code_assets: ^1.2.1
  ffi: ^2.2.0
  hippo_native_deps:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.1
  hooks: ^2.0.2
  native_toolchain_c: ^0.19.2
  objective_c: ^9.4.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  ffigen: ^20.1.1
  swiftgen: ^0.1.2
