name: desktop_autopaste
description: Federated desktop auto-paste utilities for Flutter applications.
version: 0.3.0
resolution: workspace
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"

environment:
  sdk: ">=3.12.0 < 4.0.0"
  flutter: ">=3.44.0"

dependencies:
  desktop_autopaste_linux:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.0
  desktop_autopaste_macos:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.0
  desktop_autopaste_platform_interface:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.0
  desktop_autopaste_windows:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        default_package: desktop_autopaste_linux
      macos:
        default_package: desktop_autopaste_macos
      windows:
        default_package: desktop_autopaste_windows
