name: desktop_autopaste_example
description: "Demonstrates how to use the desktop_autopaste plugin."
resolution: workspace 
publish_to: 'none' 

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  desktop_autopaste:
    path: ../
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.0
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.0
  hotkey_api:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true