name: desktop_autopaste_example
description: "Demonstrates how to use the desktop_autopaste plugin."
resolution: workspace
publish_to: "none"

environment:
  sdk: ">=3.12.0 < 4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

  desktop_autopaste:
    path: ../
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.53
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.2
  hotkey_api:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.9
  hippo_core:
    hosted: https://pub.hippolabs.org
    version: ^0.1.5
  hippo_core_flutter:
    hosted: https://pub.hippolabs.org
    version: ^0.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
