import 'dart:io';

import 'package:jnigen/jnigen.dart';

Future<void> main(List<String> args) async {
  final packageRoot = Platform.script.resolve('../');
  final androidJar = _resolveAndroidJar();

  await generateJniBindings(
    Config(
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          path: packageRoot.resolve('lib/src/generated/recorder/android_jni_bindings.dart'),
          structure: OutputStructure.singleFile,
        ),
      ),
      classes: const <String>[
        'android.content.Context',
        'android.app.Activity',
        'android.media.AudioRecord',
        'java.lang.Runnable',
      ],
      classPath: <Uri>[androidJar.uri],
      summarizerOptions: SummarizerOptions(backend: SummarizerBackend.asm),
      preamble: '// AUTO GENERATED BY JNIGEN. DO NOT EDIT.\n',
    ),
  );
}

File _resolveAndroidJar() {
  final sdkRoot = _resolveAndroidSdkRoot();
  final platformsDir = Directory('${sdkRoot.path}${Platform.pathSeparator}platforms');
  if (!platformsDir.existsSync()) {
    throw StateError('Android SDK platforms directory not found: ${platformsDir.path}');
  }

  final candidates = <({int version, File jar})>[];
  for (final entity in platformsDir.listSync(followLinks: false)) {
    if (entity is! Directory) {
      continue;
    }
    final name = entity.uri.pathSegments.isEmpty
        ? ''
        : entity.uri.pathSegments[entity.uri.pathSegments.length - 2];
    if (!name.startsWith('android-')) {
      continue;
    }
    final version = int.tryParse(name.substring('android-'.length));
    if (version == null) {
      continue;
    }
    final jar = File('${entity.path}${Platform.pathSeparator}android.jar');
    if (jar.existsSync()) {
      candidates.add((version: version, jar: jar));
    }
  }

  if (candidates.isEmpty) {
    throw StateError('No Android platform android.jar found in ${platformsDir.path}.');
  }

  candidates.sort((a, b) => b.version.compareTo(a.version));
  return candidates.first.jar;
}

Directory _resolveAndroidSdkRoot() {
  final fromEnv = Platform.environment['ANDROID_SDK_ROOT'] ?? Platform.environment['ANDROID_HOME'];
  if (fromEnv != null && fromEnv.trim().isNotEmpty) {
    final dir = Directory(fromEnv);
    if (dir.existsSync()) {
      return dir;
    }
  }

  final home = Platform.environment['HOME'];
  if (home != null && home.trim().isNotEmpty) {
    final macDefault = Directory('$home/Library/Android/sdk');
    if (macDefault.existsSync()) {
      return macDefault;
    }
  }

  throw StateError('Unable to locate Android SDK root. Set ANDROID_SDK_ROOT or ANDROID_HOME.');
}
