/// Defines a generic rpc function that can be used in implementations like the
/// supabase [ServerBloc] to call a stored procedure. Generally this class
/// should be inherited and automatically generated by a code generator.
interface class RpcFunctionDefinition<T> {
  final String functionName;
  final Map<String, dynamic> params;
  final T Function(dynamic data) responseBuilder;

  const RpcFunctionDefinition({
    required this.functionName,
    required this.params,
    required this.responseBuilder,
  });
}
