name: hippo_auth
description: Flutter package for Hippo authentication
version: 0.1.7
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter_web_auth_2: ^5.0.0
  flutter:
    sdk: flutter
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.12
  chopper: ^8.5.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  http: ^1.6.0
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  swagger_dart_code_generator: ^4.1.1
  build_runner: ^2.10.5
  chopper_generator: ^8.5.0
  json_serializable: ^6.11.2

