name: hippo_auth
description: "A new Flutter package project."
version: 0.0.1
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.0"

dependencies:
  flutter_web_auth_2: ^5.0.0-alpha.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
