name: live_audio
description: Abstracted live audio service integrations.
version: 0.2.4
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace


environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  agent_core:
    hosted: https://pub.dicto.org
    version: ^0.2.4
  dart_edge_core:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.27
  googleai_dart: ^9.0.0
  openai_dart: ^8.0.0

dev_dependencies:
  test: ^1.30.0
