name: live_audio
description: Abstracted live audio service integrations.
version: 0.1.2
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace


environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  dart_edge_core:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.17
  googleai_dart: ^7.0.0
  openai_dart: ^6.1.0
