name: hotkey_api
description: "A new Flutter plugin project."
version: 0.1.12
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.12.0 < 4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  hippo_core:
    hosted: https://pub.hippolabs.org
    version: ^0.1.5
  hippo_core_flutter:
    hosted: https://pub.hippolabs.org
    version: ^0.1.5
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.3.2
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.53

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: HotkeyApiPlugin
      windows:
        pluginClass: HotkeyApiPluginCApi
      macos:
        pluginClass: HotkeyApiPlugin
