name: hotkey_api
description: "A new Flutter plugin project."
version: 0.1.5
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  hippo_utils:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.2.0
  hippo_components:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: HotkeyApiPlugin
      windows:
        pluginClass: HotkeyApiPluginCApi
      macos:
        pluginClass: HotkeyApiPlugin
