name: dictation_support
description: "Support dictation devices using the hid_api package."
version: 0.0.1
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.10.0-0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  hid_api:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
