name: hid_api
description: Federated Human Interface Device API for Flutter desktop applications.
version: 0.1.8
homepage: https://hippolabs.org
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  hid_api_linux:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.8
  hid_api_macos:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.8
  hid_api_platform_interface:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.8
  hid_api_windows:
    hosted: https://registry.hippolabs.org/pub/internal-pub/
    version: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      linux:
        default_package: hid_api_linux
      macos:
        default_package: hid_api_macos
      windows:
        default_package: hid_api_windows
